name: Metrics
on:
  push:                # 👈 Add this line temporarily
    branches: [main]   # 👈 Add this line temporarily
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch:


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: apgosar
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          filename: github-metrics.svg
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: apgosar
          filename: github-metrics-langs.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          config_timezone: Asia/Kolkata
